export const routerPaths = {
  ROOT: "/",
  LANDING: "/landing",
  SETTINGS: "/settings",
  REGISTER: "/register",
  LOGIN: "/login",
  FORGOT_PASSWORD: "/reset",
  VERIFY_EMAIL: "/verify-email",
  CONSENT: "/consent",
  SENSITIVE_DATA: "/sensitive-data",
  CAREER_EXPLORER: "/career-explorer",
  KNOWLEDGE_HUB: "/knowledge-hub",
  KNOWLEDGE_HUB_DOCUMENT: "/knowledge-hub/:documentId",
  SKILLS_INTERESTS: "/skills-interests",
};
